import { Montserrat } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "@/lib/ApolloWrapper";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

const montserrat = Montserrat({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-montserrat",
	weight: ["400", "700", "800"], // <-- Añade '700' para Bold y '800' para ExtraBold
});
export const metadata = {
	title: "Via Car Rental",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={montserrat.className}>
			<body>
				<Header />
				<ApolloWrapper>{children}</ApolloWrapper>
				<Footer />
			</body>
		</html>
	);
}
